version: '3.8'

services:
  backend:
    build: .
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_HOST=127.0.0.1
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=csa
      - DB_PORT=3306
      - PORT=4000
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: csa
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
